# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrontendDevRelay < Formula
  desc "Powerup Frontend workflow, no more waiting for Backend to deliver"
  homepage "https://quinyx.com/"
  version "2.57.23"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quinyx/homebrew-tap/releases/download/v2.57.23/frontend-dev-relay_2.57.23_darwin_amd64.tar.gz"
      sha256 "45ddc3746a494ee84d9d4095e8c8805624d969ae21aa23dfc8f5504c59ed48fc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/quinyx/homebrew-tap/releases/download/v2.57.23/frontend-dev-relay_2.57.23_darwin_arm64.tar.gz"
      sha256 "a7a10fc19856487b99eeb96ed3de13652b1e89afde13640aab82d398e8423a77"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinyx/homebrew-tap/releases/download/v2.57.23/frontend-dev-relay_2.57.23_linux_arm64.tar.gz"
      sha256 "b43b847fee2480510bb2970322a6774be8ff9aca336e499769b74b88b599aa11"
    end
    if Hardware::CPU.intel?
      url "https://github.com/quinyx/homebrew-tap/releases/download/v2.57.23/frontend-dev-relay_2.57.23_linux_amd64.tar.gz"
      sha256 "e02226a90309281b55ffa68458b4b527a58c82e30148bbec82efdc7a16536d76"
    end
  end

  def install
    bin.install "frontend-dev-relay"
  end
end
