# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qlogtail < Formula
  desc "View Quinyx logs like a boss"
  homepage "https://quinyx.com/"
  version "50.8.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/quinyx/homebrew-tap/releases/download/v50.8.0/qlogtail_50.8.0_darwin_amd64.tar.gz"
    sha256 "9dd442d2106a27634744ac25d06b34dcc7c72d1085713259f444d6891afc4d28"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/quinyx/homebrew-tap/releases/download/v50.8.0/qlogtail_50.8.0_darwin_arm64.tar.gz"
    sha256 "1f01624eeed227ff7aaee76ca0cd24f04c90e2208ce8e6dbc78535f7b8be6695"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/quinyx/homebrew-tap/releases/download/v50.8.0/qlogtail_50.8.0_linux_amd64.tar.gz"
    sha256 "0cf96147356e0d3ffe155df36402aba4681bcf81a5aa59fbc5c222e62b38e198"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/quinyx/homebrew-tap/releases/download/v50.8.0/qlogtail_50.8.0_linux_arm64.tar.gz"
    sha256 "75e942ecfdbf91a8103c8df8b3db017a55db69c3401f80aee74f4c0a2cb86e52"
  end

  def install
    bin.install "qlogtail"
  end
end
